# Site settings
title: Bharath Srinivasan
email: admin@bharathyes.me
description: > # this means to ignore newlines until "baseurl:"
    An awesome coder, movie fanatic and a proud Macintosh owner.
    Catch here the amazing geeky stuff I do from time to time.
    From the amazing city, Chennai, TN.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bharathyes.me" # the base hostname & protocol for your site
twitter_username: s4bharath
github_username:  bharathyes
flickr_username: bharathyes

# Build settings
markdown: kramdown
